kind: Pod
apiVersion: v1
metadata:
  name: 
  namespace: kube-system
spec:
  serviceAccountName: 
  nodeName: 
  restartPolicy: Never
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: pvc1-nfs-system
  containers:
    - name: 
      image: fuyuqi1995/assistance
      command: ["python"]
      args: ["app.py","node_ip","1","1600"]
      volumeMounts:
        - mountPath: "/data/"
          name: task-pv-storage
